org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.configureondemand=false
kotlin.incremental=true
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.suppressUnsupportedCompileSdk=35
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.language=en
systemProp.user.country=US
